### ISSUE TITLE
Add `MessageEmbed`

### ISSUE THREAD

**Issue by Fyko** [discordjs/builders#10]
I suggest we add the `MessageEmbed` class. I'm more than happy to take on the task.

**Comment by monbrey** [comment]
I think this was always part of the plan so go for it.

**Comment by Fyko** [comment]
How should attachments be handled?

**Comment by kyranet** [comment]
They won't

**Comment by vladfrangu** [comment]
Attachments are a completely separate part from Embeds. They can be implemented as a separate builder, but Embeds shouldn't have any references to Attachments past docs
