### ISSUE TITLE
Switch to superstruct for validation

### ISSUE THREAD

**Issue by shinotheshino** [discordjs/builders#12]
**Is your feature request related to a problem? Please describe.**
It would be beneficial to use the [`superstruct`](https://npmjs.com/package/superstruct) package instead of `ow` for data validation.

**Describe the ideal solution**
`superstruct` is a more versatile and featureful library; it has a very intuitive, TypeScript-esque syntax, supports object schema validation, allows for defining custom types, and [a lot more](https://docs.superstructjs.org/) in addition to what we currently can do with `ow`. I believe `superstruct` would be a much better validation library overall.

Additionally, `superstruct` has built-in support for TypeScript, exporting functions like `is(x, struct): x is struct` and `assert(x, struct): asserts x is struct` which would allow for inline inference of data types. You can also generate a type from a `Schema` object very easily, reducing data duplication as you only need to write the schema, which will automatically generate a type for you:
```ts
type StructType<T> = T extends Struct<infer R> ? R : never;

const MyStruct = object({
  id: Snowflake(),
  something: number(),
});

export type MyType = StructType<typeof MyStruct>;
// MyType = { id: Snowflake; something: number };
```

**Comment by jonahsnider** [comment]
Switching from `ow` is probably a good idea, although it might be worth looking at a few other TypeScript schema validation libraries and deciding what's best for this project.

Some popular libraries to consider in addition to Superstruct:

- [Zod](https://github.com/colinhacks/zod#readme)
- [TypeBox](https://github.com/sinclairzx81/typebox#readme)
- [Yup](https://github.com/jquense/yup#readme)

**Comment by vladfrangu** [comment]
Love the feedback, and thanks for sharing other libraries that can achieve this, but what's wrong with `ow` if I may ask? Would love to know more :D
