### ISSUE TITLE
Can't add permissions

### ISSUE THREAD

**Issue by faabmaster** [discordjs/builders#27]
This is likely already in the pipeline to be added, but there's no function to add permissions to commands at this time.

**Comment by faabmaster** [comment]
Had a brainfart, misunderstood slash commands and how they work.

**Comment by Cy63N70** [comment]
As I know, `defaultPermission: false` in slash command data makes it unusable for non-admin members in a guild, So I'd like to see something like `setDefaultPermissions(true)` in slash command builders

**Comment by Megatank58** [comment]
The `setDefaultPermission(boolean)` is available on SlashCommandBuilder

**Comment by NMW03** [comment]
> As I know, `defaultPermission: false` in slash command data makes it unusable for non-admin members in a guild, So I'd like to see something like `setDefaultPermissions(true)` in slash command builders

#19

**Comment by fivekWBassMachine** [comment]
> The `setDefaultPermission(boolean)` is available on SlashCommandBuilder

And I guess it's not working. I've used the example at https://discordjs.guide/creating-your-bot/command-handling.html#individual-command-files and created an extra file for each command.

The command file (`/CommandStatus.js`):
```js
const { SlashCommandBuilder } = require('@discordjs/builders');

module.exports = {
    data: new SlashCommandBuilder()
        .setName('status')
        .setDescription('Returns information about the bots health status.')
        .setDefaultPermission(false), // should disable the command for everyone
    permission: 1, // irrelevant, it's for my permission system
    async execute(interaction) {
        // command stuff, irrelevant here
    }
};

async function wait(ms) {
    await new Promise(resolve => setTimeout(resolve, ms));
}
```
Le exception:
```
/CommandStatus.js:7
        .setDefaultPermission(false),
         ^

TypeError: (intermediate value).setName(...).setDescription(...).setDefaultPermission is not a function
    at Object.<anonymous> (/CommandStatus.js:7:10)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at *my main class*
```
in my main class, i registered the commands as described here: https://discordjs.guide/creating-your-bot/command-handling.html#reading-command-files the error is thrown in the line where i included `/CommandStatus.js`

setting `SlashCommand.defaultPermission` directly did not work either, so my solution was to add `default_permission` after calling `SlashCommand.toJSON` before pushing the json object to the commands array:

```js
const data = command.data.toJSON();
data.default_permission = false;
commands.push(data);
```

**Comment by Khasms** [comment]
@fivekWBassMachine You need to update your builders version to v0.6.

**Comment by fivekWBassMachine** [comment]
thanks. no clue why, but in my package.json had no @discordjs/builders dependency. ive installed it manually  and than SlashCommand.defaultPermission worked as expected. the other problem to enable permissions again for some roles is solved either (althought the guide helped me with nothing)

**Comment by vladfrangu** [comment]
Since it seems like the issue at hand is solved, I'm going to close this. If that's not the case, please follow up and I'll reopen this for you :D
