### ISSUE TITLE
Interface for SlashCommandBuilder#toJSON()

### ISSUE THREAD

**Issue by mahyarmirrashed** [discordjs/builders#32]
**Is your feature request related to a problem? Please describe.**
I create my slash commands in each of their own files. Each file exports a constant variable whose value is constructed using the slash command builder at runtime.

**Describe the ideal solution**
Add something like this in `SlashCommandBuilder.d.ts`:
```ts
type SlashCommandJSON = {
  name: string;
  description: string;
  options: APIApplicationCommandOption[];
  default_permission: boolean | undefined;
};

export default SlashCommandJSON;
```

**Describe alternatives you've considered**
The alternative is for me to create that file for myself and just reuse it for other projects.

**Additional context**
No additional context to provide.

**Comment by vladfrangu** [comment]
This is a double bug: The return type for SlashCommandBuilder#toJSON isn't properly typed to the API data, as well as discord.js not supporting raw data (which is a different issue altogether, and should be opened in that repository!)

**Comment by DTrombett** [comment]
Oh is there a type in the `discord-api-types` package related to the raw command data accepted by Discord? In that case the return type of `toJSON` could be changed to this type and the `create` (`set`, etc...`) djs' method could also accept it as parameter. I see that it works as expected if I ignore the ts error so the source code is already compatible (or maybe not everything is supported?)

**Comment by vladfrangu** [comment]
> I see that it works as expected if I ignore the ts error so the source code is already compatible (or maybe not everything is supported?)

It's """compatible""", default_permissions won't be respected by d.js right now 😓

**Comment by suneettipirneni** [comment]
So I may be missing something but there is no dedicated client-side type for application command data in `discord-api-types`. `APIApplicationCommand` represents command data sent back from the serve (hence it requires and `id` and `applicationId`. I think the first step would be adding a client-side application command type to `discord-api-types`.

**Comment by vladfrangu** [comment]
Sure there is. RESTPostAPIApplicationCommandData or something aching to that

**Comment by suneettipirneni** [comment]
Alright, disregard my last comment

**Comment by mahyarmirrashed** [comment]
Any update on this issue?

**Comment by Khasms** [comment]
Fix got merged in #34.

**Comment by MarcusOtter** [comment]
FYI I couldn't figure out how to solve this without `ReturnType<SlashCommandBuilder["toJSON"]>`

It's the `options` property that's causing issues. Here's a few things I tried, hopefully this helps in debugging/understand the issue:
<details>
<summary><code>options: APIApplicationCommandOption[];</code></summary>
<pre lang="ts">
import { SlashCommandBuilder } from "@discordjs/builders";
import { APIApplicationCommandOption } from "discord-api-types/payloads/v9";
...
async getInfo():
	Promise<{
		name: string;
		description: string;
		options: APIApplicationCommandOption[];
		default_permission: boolean | undefined;
	}> {
	return new SlashCommandBuilder()
		.setName("ping")
		.setDescription("Replies with pong")
		.toJSON();
},
</pre>
Error:
<pre>
Type 'ApplicationCommandOptionType.String' is not assignable to type 'ApplicationCommandOptionType.String | ApplicationCommandOptionType.Integer | ApplicationCommandOptionType.Number'.
</pre>
</details>

<details>
<summary><code>options: RESTPostAPIApplicationCommandsJSONBody[];</code></summary>
<pre lang="ts">
import { SlashCommandBuilder } from "@discordjs/builders";
import { RESTPostAPIApplicationCommandsJSONBody } from "discord-api-types";
...
async getInfo():
	Promise<{
		name: string;
		description: string;
		options: RESTPostAPIApplicationCommandsJSONBody[];
		default_permission: boolean | undefined;
	}> {
	return new SlashCommandBuilder()
		.setName("ping")
		.setDescription("Replies with pong")
		.toJSON();
},
</pre>
Error:
<pre>
Type 'ApplicationCommandOptionType.String' is not assignable to type 'ApplicationCommandType.ChatInput | undefined'
</pre>
</details>

Tried a handful of other types that I saw being thrown around but couldn't find anything that worked. Would love to get any pointers what type it should really be (and most importantly, how I was supposed to figure that out).

I am using:
- discord.js: `13.1.0`
- discord-api-types: `0.23.1`
- @discordjs/builders: `0.6.0`

I don't mean to sound rude, but the developer experience with DJS types haven't been great so far, it feels like it should be easier than this
![image](https://user-images.githubusercontent.com/35617441/133942377-16fe9473-bb5d-4ec3-a9f3-fd7236c29bbe.png)

Let me know if I should open another issue for this. Seemed like it was relevant to this one though.

**Comment by suneettipirneni** [comment]
> FYI I couldn't figure out how to solve this without `ReturnType<SlashCommandBuilder["toJSON"]>`
> 
> It's the `options` property that's causing issues. Here's a few things I tried, hopefully this helps in debugging/understand the issue:
> 
> Click to see code and errors for `options: APIApplicationCommandOption[];`
> ```ts
> import { SlashCommandBuilder } from "@discordjs/builders";
> import { APIApplicationCommandOption } from "discord-api-types/payloads/v9";
> ...
> async getInfo():
> 	Promise<{
> 		name: string;
> 		description: string;
> 		options: APIApplicationCommandOption[];
> 		default_permission: boolean | undefined;
> 	}> {
> 	return new SlashCommandBuilder()
> 		.setName("ping")
> 		.setDescription("Replies with pong")
> 		.toJSON();
> },
> ```
> 
> Error:
> Type 'ApplicationCommandOptionType.String' is not assignable to type 'ApplicationCommandOptionType.String | ApplicationCommandOptionType.Integer | ApplicationCommandOptionType.Number'.
> Click to see code and errors for `options: RESTPostAPIApplicationCommandsJSONBody[];`
> ```ts
> import { SlashCommandBuilder } from "@discordjs/builders";
> import { RESTPostAPIApplicationCommandsJSONBody } from "discord-api-types";
> ...
> async getInfo():
> 	Promise<{
> 		name: string;
> 		description: string;
> 		options: RESTPostAPIApplicationCommandsJSONBody[];
> 		default_permission: boolean | undefined;
> 	}> {
> 	return new SlashCommandBuilder()
> 		.setName("ping")
> 		.setDescription("Replies with pong")
> 		.toJSON();
> },
> ```
> 
> Error:
> Type 'ApplicationCommandOptionType.String' is not assignable to type 'ApplicationCommandType.ChatInput | undefined'
> Tried a handful of other types that I saw being thrown around but couldn't find anything that worked. Would love to get any pointers what type it should really be (and most importantly, how I was supposed to figure that out).
> 
> I am using:
> 
> * discord.js: `13.1.0`
> * discord-api-types: `0.23.1`
> * @discordjs/builders: `0.6.0`
> 
> I don't mean to sound rude, but the developer experience with DJS types haven't been great so far, it feels like it should be easier than this
> ![image](https://user-images.githubusercontent.com/35617441/133942377-16fe9473-bb5d-4ec3-a9f3-fd7236c29bbe.png)
> 
> Let me know if I should open another issue for this. Seemed like it was relevant to this one though.

Have you tried setting the return type of your function to `Promise<RESTPostAPIApplicationCommandsJSONBody>`?

**Comment by MarcusOtter** [comment]
Err actually I see now that the fix was merged 22 days ago but the version I'm on (`0.6.0`) was released 26 days ago. Guess I'm waiting for the next version?

**Comment by MarcusOtter** [comment]
@suneettipirneni Yep, my message shows both the code and the error for `RESTPostAPIApplicationCommandsJSONBody`. Click the arrows with that type

**Comment by suneettipirneni** [comment]
> @suneettipirneni Yep, my message shows both the code and the error for `RESTPostAPIApplicationCommandsJSONBody`. Click the arrows with that type

Yes but that's incorrect, the command itself should be represented by `RESTPostAPIApplicationCommandsJSONBody`, not the options. I'm saying to change the entire:

```ts
Promise<{
	name: string;
	description: string;
	options: RESTPostAPIApplicationCommandsJSONBody[];
	default_permission: boolean | undefined;
}>
```

to

```ts
Promise<RESTPostAPIApplicationCommandsJSONBody>
```

**Comment by MarcusOtter** [comment]
Ah gotcha, sorry. Same problem though I'm afraid
```
Type 'ApplicationCommandOptionType.String' is not assignable to type 'ApplicationCommandOptionType.String | ApplicationCommandOptionType.Integer | ApplicationCommandOptionType.Number'
```

**Comment by suneettipirneni** [comment]
> Ah gotcha, sorry. Same problem though I'm afraid
> 
> ```
> Type 'ApplicationCommandOptionType.String' is not assignable to type 'ApplicationCommandOptionType.String | ApplicationCommandOptionType.Integer | ApplicationCommandOptionType.Number'
> ```
Ok yeah I can reproduce this on the latest release, however the most up to date code works with this. I would just augment the module return type for now in a declaration file, until the release is made.

**Comment by MarcusOtter** [comment]
Thanks!

**Comment by mahyarmirrashed** [comment]
> Sure there is. RESTPostAPIApplicationCommandData or something aching to that

This now fails in the latest version of discord-api-types (0.23.1). However, for 0.22.0, it still works.
