### ISSUE TITLE
ApplicationCommand builder

### ISSUE THREAD

**Issue by ZatsuneNoMokou** [discordjs/builders#37]
**Is your feature request related to a problem? Please describe.**
Could it be possible to have a builder compatible with https://discord.js.org/#/docs/main/stable/class/ApplicationCommand ?

**Describe the ideal solution**
A build like the existing SlashCommandBuilder but that output something usable directly with discord.js without having to create a REST instance ourself (and that typescript will be happy of).

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by vladfrangu** [comment]
Pretty sure this has been fixed already with recent versions of discord.js and /builders. As such, I will close this issue, but if you noticed that this isn't the case, please follow up!
