### ISSUE TITLE
Add autocomplete to options

### ISSUE THREAD

**Issue by callumok2004** [discordjs/builders#50]
### Feature

Discord.js has recently added support for autocomplete, but I am being held back by this library, not including support for it, please add this!

### Ideal solution or implementation

I am sure a solution would be as simple as any other option!

**Comment by iCrawl** [comment]
First:
You aren't held back at all to use it; you can use autocomplete fine without a builder.

Second:
It's not always as simple, as a PR on this has already been attempted by a user and they encountered some problems with it that weren't "easily" solvable.

**Comment by Khasms** [comment]
Support for autocomplete was released in v0.9.0. This issue can be closed.
