### ISSUE TITLE
Context Menus

### ISSUE THREAD

**Issue by thesadnoodle** [discordjs/builders#51]
### Feature

Please add context menus to the package

### Ideal solution or implementation

So maybe add an option were we could choose between / and content when making our code. Here is an example

```
const { SlashCommandBuilder } = require('@discordjs/builders');
const Discord = require('discord.js')

module.exports = {
	data: new SlashCommandBuilder()
		.setName('ping')
		.setDescription('Replies with Pong!')
                .setType(type),
	async execute(interaction) {
		await interaction.reply('Pong')	
	},
};
```

**Comment by Jiralite** [comment]
Context menus are already here since 0.7.0? Are you asking about something else?
https://github.com/discordjs/builders/releases/tag/v0.7.0

**Comment by thesadnoodle** [comment]
My apologies! I was not aware of this. Is there any documentation on how to use it as I was not able to find any?

**Comment by almostSouji** [comment]
Builder documentation is now available on the main docs page (select in the top dropdown) at <https://discord.js.org/#/docs/builders/stable/class/ContextMenuCommandBuilder>
