### ISSUE TITLE
ESM TypeError: Cannot read properties of undefined (reading 'minLength') 

### ISSUE THREAD

**Issue by KhafraDev** [discordjs/builders#54]
### Issue description

This issue is caused by ow, as the code below shows.

1. Install @discordjs/builders@0.8.1
2. Set up an esm project
3. Try the sample code

This issue did not occur on v0.7.x.
edit: https://github.com/sindresorhus/ow/issues/215

### Code sample

```typescript
import { SlashCommandBuilder } from '@discordjs/builders';
new SlashCommandBuilder();

// or

import ow from 'ow';
ow.string.minLength(1); // ow.string is undefined
```

### @discordjs/builders version

0.8.1

### Node.js version

16.13.0

### Operating system

Windows

### Priority this issue should have

High (immediate attention needed)

**Comment by DuckingElias** [comment]
Temporary solution:

1. Type `npm shrinkwrap`. This deletes your package-lock.json and creates an package-shrinkwrap.json
2. Inside the package-shrinkwrap.json, search for `node_modules/@discordjs/builders`
3. Under `dependencies` of `node_modules/@discordjs/builders`, change the version of ow to `^0.27.0`
4. Delete your node_modules and type `npm install`

**Comment by Favna** [comment]
Or temporary solution for yarn users add to your package.json
```json
"resolutions": {
  "ow": "0.27.0"
}
```

**Comment by Gamer025** [comment]
Did the linked PR actually fix this issue?
I also had this problem yesterday and updated to 0.8.2 today, but im still getting the same error when trying to import @discordjs/builders.
Already reset my modules folder to make sure its using ow 0.27.0 and builder 0.8.2
Someone in the linked ow issue (https://github.com/sindresorhus/ow/issues/215) also said they have this problem with 0.27.0
![image](https://user-images.githubusercontent.com/33846895/139594896-87abcb45-39cd-4a78-82d2-e7f9eb466871.png)
I also tried creating a completely new Node project and installed only ow@0.27.0 and tried to run a mjs file only containing:
```js
import ow from 'ow';
ow.string.minLength(1);
```
Still resulted in `TypeError: Cannot read properties of undefined (reading 'minLength')`
![image](https://user-images.githubusercontent.com/33846895/139595059-ee5abfcc-c0a1-418b-9146-24cae8018df9.png)

**Comment by KhafraDev** [comment]
no it didn't, but it took some time for a real fix @Gamer025 sorry about that

**Comment by NateFlynn-Silktide** [comment]
Is there any solution for this at the moment? I'm getting the same error on a fresh build with `@discord/builders@0.8.2` and `ow@0.27.0`.

Got plenty of other bits to be working on in the meantime if the fix for this is still a way off 🙂

**Comment by KhafraDev** [comment]
there is a pr to fix this linked above, in the meantime you can force install an older builders version with `npm i @discordjs/builders@0.7.0`

**Comment by VIKTORVAV99** [comment]
Why was this issue closed when the issue itself hasn't been resolved?

I was about to create a new issue for it before I looked at pull requests where #56 linked here.

**Comment by almostSouji** [comment]
The author of said PR used a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) which is triggered on merge into the main branch.

**Comment by VIKTORVAV99** [comment]
Ah that makes sense, thanks for reopening it.

**Comment by RamennBowls** [comment]
If this helps at all, even after having 'ow' downgraded to `^0.27.0`, the error still occurs for me but only when importing it using ES6.
```js
import { SlashCommandBuilder } from '@discordjs/builders'
```

When using 'require', the error doesn't appear.
```js
const { SlashCommandBuilder } = require('@discordjs/builders')
```

**Comment by favna** [comment]
> If this helps at all, even after having 'ow' downgraded to `^0.27.0`, the error still occurs for me but only when importing it using ES6.
> 
> ```js
> import { SlashCommandBuilder } from '@discordjs/builders'
> ```
> 
> When using 'require', the error doesn't appear.
> 
> ```js
> const { SlashCommandBuilder } = require('@discordjs/builders')
> ```

There is no `require` in ESM. Anyway there are PRs #56 and #58 and whichever will end up being merged will mean `ow` is gone and this problem is resolved.

**Comment by ze** [comment]
#58 Fixed the bug for me! Now the discordjs package needs to be updated to use 0.9.0 instead of 0.8.2!
